SitioMedico/CEHN/urls.py
from django.urls import path
from . import views


from .views import Home, PacientCreate, MedicCreate, AdminCreate, CitasListas, CancelarCita, ConfirmConsulView, \
    Query_Medic, Query_Interval, Query_Avail, AssignView, ConsultasListas, listaMedicsView, ConsulUpdateView, \
    MedicaView, AvailabilityCreateView, MissAppoView, ListaCitasView, AplazaAppoView, GetMedic, SetAvailableAppointments

app_name = 'CEHN'
urlpatterns = [
    path('medics/', Query_Medic.as_view(), name='medic'),
    path('intervals/', Query_Interval.as_view(), name='intervals'),
    path('avail/assigns/', AssignView.as_view(), name="assigns"),
    path('asignar/', AssignView.as_view(), name="assign"),
    path('avail/', Query_Avail.as_view(), name='availabilities'),
    path('', Home.as_view(), name="home"),
    path('', views.login, name="login"),
    path('admin_registered/', views.admin_registered, name="admin_registered"),
    path('medic_registered/', views.medic_registered, name="medic_registered"),
    path('patient_registered/', views.patient_registered, name="patient_registered"),
    path('registrar/paciente', PacientCreate.as_view(), name="registar_paciente"),
    path('registrar/medico', MedicCreate.as_view(), name="registrar_medico"),
    path('registrar/admin', AdminCreate.as_view(), name="registrar_admin"),
    path('citas/', CitasListas.as_view(), name='citas'),
    path('cancelar/<pk>', CancelarCita.as_view(), name='cancelar'),
    path('aplazar/<pk>', AplazaAppoView.as_view(), name='aplazar'),
    path('create/availability/',AvailabilityCreateView.as_view(), name='create_availability'),
    path('consultas', ConsultasListas.as_view() ,name='consultas'),
    path('confirm/<apo>', ConfirmConsulView.as_view() ,name='confirmconsul'),
    path('medicos/',listaMedicsView.as_view(),name='medicos'),
    path('consulta/<pk>',ConsulUpdateView.as_view(), name='actualconsul'),
    path('medicamentos/<consult>', MedicaView.as_view(), name='medicamentos'),
    path('miss/<pk>', MissAppoView.as_view(), name='citaperdida'),
    path('listacitas/<medic>',ListaCitasView.as_view(), name='listacitas')
    # path('', views.index, name="index"),
    #path('dispo/<medic>',Dispo.as_view(),name='dispo'),
    #path('citas/<pacient>', CitasListas.as_view(), name='citas'),
    #url(r'cancelar/(?P<pk>\d+)$', CancelarCita.as_view(), name='cancelar'),
    # path('dispo/<medic>',Dispo.as_view(),name='dispo'),
    # path('citas/<pacient>', CitasListas.as_view(), name='citas'),
    # url(r'cancelar/(?P<pk>\d+)$', CancelarCita.as_view(), name='cancelar'),
    # path('dispo/<medic>',Dispo.as_view(),name='dispo'),
    # path('citas/<pacient>', CitasListas.as_view(), name='citas'),
    # url(r'cancelar/(?P<pk>\d+)$', CancelarCita.as_view(), name='cancelar'),
    # path('assign/', GetMedic.as_view(), name='assigning'),
    # path('assign/assigning/', SetAvailableAppointments.as_view(), name='assigning'),
]

SitioMedico/SitioMedico/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic.base import TemplateView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('django.contrib.auth.urls')),
    path('', include('CEHN.urls')),
    #path('assign/', TemplateView.as_view(template_name='assign.html'), name='assign'),
    path('', TemplateView.as_view(template_name='home.html'), name='home')
]

SitioMedico/templates/Assign/assign.html
{% extends 'base/base.html' %}

{% load static %}

{% block title %}APARTAR CITAS{% endblock %}
<body>
{% block body %}

<div class="login100-form-title">
    <div class="login100-form-title">
        <a style="padding-left: 750px;" href="{% url 'logout' %}?next=/login"><input type="image" height="35px"
                                                                                     src="{% static 'CEHN/images/icons/iconfinder_power_926636.png' %}"></a>

    </div>
    {% if object_list %}
    <form class="" method="post" action="/avail/">
        <div class="cont_label text-left">
            <label class="">SELECCIONA TU MÉDICO:</label>
        </div>
        <br>
        {% csrf_token %}
        <select class="form-control form-control" name="id_Medic">
            {% for x in object_list %}
            <option value="{{ x.id_Medic }}" name="name_medic">{{ x.name }}{{" "}}{{ x.lastname1 }}</option>
            {% endfor %}
        </select><br><br>
        {% endif %}
        <div class="">
            <div class="cont_label text-left">
                <label class="">SELECCIONA LA FECHA:</label>
            </div>
            <br>
            <input type="date" name="date" style="cursor:pointer;" required>
            <input type="submit" class='btn btn-dark' name="send" style="cursor:pointer;" value="APARTAR">
        </div>
    </form>
    <br>
    <a class="txt2" href="{% url 'CEHN:citas' %}">
        Volver
    </a>
</div>

{% endblock %}

</body>
</html>

SitioMedico/templates/Assign/avail.html
{% extends 'base/base.html' %}

{% load static %}

{% block title %}AVAIL{% endblock %}
<body>
{% block container %}
<div class="container-login100 fondoContainer">
    {% block wrap %}
    <div class="wrap-login100" style="padding-top: 60px;">
        {% block body %}

        {% if qsea %}
        <div class="login100-form-title">
            <div class="login100-form-title">
                <div class="login100-form-title">
                    <a style="padding-left: 750px;" href="{% url 'logout' %}?next=/login"><input type="image"
                                                                                                 height="35px"
                                                                                                 src="{% static 'CEHN/images/icons/iconfinder_power_926636.png' %}"></a>

                </div>
                <form class="login100-form-title" method="POST" action="/asignar/">
                    {% csrf_token %}
                    <label>MEDICO</label>
                    <input class="form-control" hidden name="medico" type="text" value="{{ id_Medic.id_Medic }}">
                    <input class="form-control" disabled type="text" value="{{ id_Medic }}"><br><br>
                    <label>FECHA</label>
                    <input class="form-control" hidden name="fecha" type="text" value="{{ date }}">
                    <input class="form-control" disabled type="text" value="{{ date }}"><br><br>
                    <label>OFICINA</label>
                    <input class="form-control" hidden name="oficina" type="text" value="{{ id_off.id_off }}">
                    <input class="form-control" disabled type="text" value="{{ id_off }}">
                    <br><br>
                    <p>SELECCIONA LA HORA DE TU CITA</p>
                    <select class="form-control" name="intervalo">
                        {% for x in qsea %}
                        <option value="{{x.id_inter1.id_inter}}">{{ x.id_inter1 }}</option>
                        {% endfor %}
                    </select>
                    <br>
                    <br>
                    <center>
                        <input class="btn btn-primary" style="cursor: pointer;" type="submit" value="ASIGNAR">
                    </center>
                    <a class="txt2" href="{% url 'CEHN:medic' %}">Volver</a>
                </form>
            </div>
            {% else %}
            <div class="login100-form-title">
                <a style="padding-left: 750px;" href="{% url 'logout' %}?next=/login"><input type="image"
                                                                                             height="35px"
                                                                                             src="{% static 'CEHN/images/icons/iconfinder_power_926636.png' %}"></a>

            </div>
            <div class="login100-form-title">
                <h2>No hay disponibilidad con este medico para esa fecha</h2><br>
                <a class="btn btn-info" href="{% url 'CEHN:medic' %}">Volver</a>
            </div>
            {% endif %}
        </div>
    </div>
</div>
{% endblock %}
{% endblock %}
{% endblock %}
</body>

SitioMedico/templates/Assign/created_appointment.html
{% extends 'base/base.html' %}

{% load static %}

{% block title %}CITA APARTADA{% endblock %}
<body>
{% block container %}
<div class="container-login100 fondoContainer">
    {% block wrap %}
    <div class="wrap-login100" style="padding-top: 60px;">
        {% block body %}
        <div class="login100-form-title">
            <a style="padding-left: 750px;" href="{% url 'logout' %}?next=/login"><input type="image"
                                                                                         height="35px"
                                                                                         src="{% static 'CEHN/images/icons/iconfinder_power_926636.png' %}"></a>

        </div>
        <div class="login100-form-title">
            {% if message and cita %}
            <h1>{{ message }}</h1>
            <br><br>
            <p class="text_appo"><b>Fecha, Hora y Médico :</b> {{ cita.id_aval1 }}</p>
            <p class="text_appo"><b>Nombre del Paciente:</b> {{ cita.id_pac1 }}</p>
            <p class="text_appo">El estado de la Cita es <b>SEPARADA</b>, si no puede asisitir por favor cancelela con
                mínimo 24 horas de anticipación</p><br><br>
            {% endif %}
            <a class="btn btn-info" href="{% url 'CEHN:citas' %}">Citas Apartadas</a>
        </div>
    </div>
</div>
{% endblock %}
{% endblock %}
{% endblock %}
</body>

SitioMedico/templates/Assign/hours.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
    <table border="1">
        <thead>
            <tr>
                <th>ID</th>
                <th>HORA INICIAL CITA</th>
                <th>HORA FINAL CITA</th>
            </tr>
        </thead>
        {% if object_list %}
        <tbody>
            {% for y in object_list %}
            <tr>
                <td>{{ y.id_inter }}</td>
                <td>{{ y.hour_start}}</td>
                <td>{{ y.hour_finish}}</td>
            </tr>
            {% endfor %}
        </tbody>
        {% endif %}
    </table>
</body>
</html>