SitioMedico/CEHN/urls.py
from django.urls import path
from . import views


from .views import Home, PacientCreate, MedicCreate, AdminCreate, CitasListas, CancelarCita, ConfirmConsulView, \
    Query_Medic, Query_Interval, Query_Avail, AssignView, ConsultasListas, listaMedicsView, ConsulUpdateView, \
    MedicaView, AvailabilityCreateView, MissAppoView, ListaCitasView, AplazaAppoView, GetMedic, SetAvailableAppointments

app_name = 'CEHN'
urlpatterns = [
    path('medics/', Query_Medic.as_view(), name='medic'),
    path('intervals/', Query_Interval.as_view(), name='intervals'),
    path('avail/assigns/', AssignView.as_view(), name="assigns"),
    path('asignar/', AssignView.as_view(), name="assign"),
    path('avail/', Query_Avail.as_view(), name='availabilities'),
    path('', Home.as_view(), name="home"),
    path('', views.login, name="login"),
    path('admin_registered/', views.admin_registered, name="admin_registered"),
    path('medic_registered/', views.medic_registered, name="medic_registered"),
    path('patient_registered/', views.patient_registered, name="patient_registered"),
    path('registrar/paciente', PacientCreate.as_view(), name="registar_paciente"),
    path('registrar/medico', MedicCreate.as_view(), name="registrar_medico"),
    path('registrar/admin', AdminCreate.as_view(), name="registrar_admin"),
    path('citas/', CitasListas.as_view(), name='citas'),
    path('cancelar/<pk>', CancelarCita.as_view(), name='cancelar'),
    path('aplazar/<pk>', AplazaAppoView.as_view(), name='aplazar'),
    path('create/availability/',AvailabilityCreateView.as_view(), name='create_availability'),
    path('consultas', ConsultasListas.as_view() ,name='consultas'),
    path('confirm/<apo>', ConfirmConsulView.as_view() ,name='confirmconsul'),
    path('medicos/',listaMedicsView.as_view(),name='medicos'),
    path('consulta/<pk>',ConsulUpdateView.as_view(), name='actualconsul'),
    path('medicamentos/<consult>', MedicaView.as_view(), name='medicamentos'),
    path('miss/<pk>', MissAppoView.as_view(), name='citaperdida'),
    path('listacitas/<medic>',ListaCitasView.as_view(), name='listacitas')
    # path('', views.index, name="index"),
    #path('dispo/<medic>',Dispo.as_view(),name='dispo'),
    #path('citas/<pacient>', CitasListas.as_view(), name='citas'),
    #url(r'cancelar/(?P<pk>\d+)$', CancelarCita.as_view(), name='cancelar'),
    # path('dispo/<medic>',Dispo.as_view(),name='dispo'),
    # path('citas/<pacient>', CitasListas.as_view(), name='citas'),
    # url(r'cancelar/(?P<pk>\d+)$', CancelarCita.as_view(), name='cancelar'),
    # path('dispo/<medic>',Dispo.as_view(),name='dispo'),
    # path('citas/<pacient>', CitasListas.as_view(), name='citas'),
    # url(r'cancelar/(?P<pk>\d+)$', CancelarCita.as_view(), name='cancelar'),
    # path('assign/', GetMedic.as_view(), name='assigning'),
    # path('assign/assigning/', SetAvailableAppointments.as_view(), name='assigning'),
]

SitioMedico/SitioMedico/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic.base import TemplateView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('django.contrib.auth.urls')),
    path('', include('CEHN.urls')),
    #path('assign/', TemplateView.as_view(template_name='assign.html'), name='assign'),
    path('', TemplateView.as_view(template_name='home.html'), name='home')
]

SitioMedico/CEHN/views.py
from django.http import request, HttpResponse
from django.contrib.auth.mixins import LoginRequiredMixin
from django.utils.decorators import method_decorator
from .decorator import medic_required, pacient_required, admin_required
from django.shortcuts import get_object_or_404, render, redirect
from django.http import HttpResponseRedirect
from django.urls import reverse_lazy
from datetime import date

from django.views.generic import CreateView, TemplateView, ListView, UpdateView, View
from .models import AccountUser, Appointment, Availability, Pacient, Medic, Interval, Consultation, DetalleMedicamento
from .forms import PacientSignUPForm, PacientForm, MedicSignUPForm, MedicForm, AdminSignUpForm, \
    AvailabilityForm, AppointmentForm, ConfirmConsulForm, ListaMedicsForm, ActualConsulForm, \
    MedicaForm, AvailabilityFormFull, SetAvailableAppointments, MissAppoForm, ListaCitasForm

# Create your views here.


def index(request):
    return render(request, 'index.html')


def login(request):
    return render(request, 'registration/login.html')


def patient_registered(request):
    return render(request, 'register/patient_registered.html')


def medic_registered(request):
    return render(request, 'register/medic_registered.html')


def admin_registered(request):
    return render(request, 'register/admin_registered.html')


class Home(LoginRequiredMixin, TemplateView):
    login_url = '/login/'
    template_name = 'home.html'


@method_decorator([admin_required], name='dispatch')
class PacientCreate(LoginRequiredMixin, CreateView):
    login_url = '/login/'
    model = Pacient
    template_name = 'register/patient_register.html'
    form_class = PacientForm
    second_form_class = PacientSignUPForm
    success_url = reverse_lazy('CEHN:patient_registered')

    def get_context_data(self, **kwargs):
        context = super(PacientCreate, self).get_context_data(**kwargs)
        if "form" not in context:
            context['form'] = self.form_class(self.request.GET)
        if "form1" not in context:
            context['form1'] = self.second_form_class(self.request.GET)
        return context

    def post(self, request, *args, **kwargs):
        self.object = self.get_object
        form = self.form_class(request.POST)
        form1 = self.second_form_class(request.POST)
        if form.is_valid() and form1.is_valid():
            pacient = form.save(commit=False)
            pacient.userFK = form1.save()
            pacient.save()
            return HttpResponseRedirect(self.get_success_url())
        else:
            return self.render_to_response(
                self.get_context_data(form=form, form1=form1, message="Paciente registrado con exito!"))


@method_decorator([admin_required], name='dispatch')
class MedicCreate(LoginRequiredMixin, CreateView):
    login_url = '/login/'
    model = Medic
    template_name = 'register/medic_register.html'
    form_class = MedicForm
    second_form_class = MedicSignUPForm
    success_url = reverse_lazy('CEHN:medic_registered')

    def get_context_data(self, **kwargs):
        context = super(MedicCreate, self).get_context_data(**kwargs)
        if "form" not in context:
            context['form'] = self.form_class(self.request.GET)
        if "form1" not in context:
            context['form1'] = self.second_form_class(self.request.GET)
        return context

    def post(self, request, *args, **kwargs):
        self.object = self.get_object
        form = self.form_class(request.POST)
        form1 = self.second_form_class(request.POST)
        if form.is_valid() and form1.is_valid():
            medic = form.save(commit=False)
            medic.userFK = form1.save()
            medic.save()
            return HttpResponseRedirect(self.get_success_url())
        else:
            return self.render_to_response(self.get_context_data(form=form, form1=form1))


@method_decorator([admin_required], name='dispatch')
class AdminCreate(LoginRequiredMixin, CreateView):
    login_url = '/login/'
    model = AccountUser
    template_name = 'register/admin_register.html'
    form_class = AdminSignUpForm
    success_url = reverse_lazy('CEHN:admin_registered')


@method_decorator([pacient_required], name='dispatch')
class CitasListas(LoginRequiredMixin, ListView):
    login_url = '/login/'
    model = Appointment
    template_name = 'CEHN/citas.html'

    def get_queryset(self):
        self.pac = get_object_or_404(Pacient, userFK_id=self.request.user.id)
        return Appointment.objects.filter(id_pac1=self.pac.id, appointment='SP') | Appointment.objects.filter(id_pac1=self.pac.id, appointment='CF')


@method_decorator([pacient_required], name='dispatch')
class CancelarCita(LoginRequiredMixin, UpdateView):
    login_url = '/login/'
    model = Appointment
    second_model = Availability
    template_name = 'CEHN/cancelarcita.html'
    form_class = AppointmentForm
    second_form_class = AvailabilityForm
    success_url = reverse_lazy('CEHN:citas')

    # in this case I use two models in a view and a template
    def get_context_data(self, **kwargs):
        context = super(CancelarCita, self).get_context_data(**kwargs)
        pk = self.kwargs.get('pk', 0)
        cancelacion = self.model.objects.get(id_appo=pk)
        disponibilidad = self.second_model.objects.get(id_aval=(cancelacion.id_aval1).id_aval)
        if 'form' not in context:
            context['form'] = self.form_class()
        if 'form2' not in context:
            context['form2'] = self.second_form_class(instance=disponibilidad)
        context['id'] = pk
        return context

    def post(self, request, *args, **kwargs):
        self.object = self.get_object
        cancelacion = self.model.objects.get(id_appo=kwargs['pk'])
        disponibilidad = self.second_model.objects.get(id_aval=(cancelacion.id_aval1).id_aval)
        form = self.form_class(request.POST, instance=cancelacion)
        form2 = self.second_form_class(request.POST, instance=disponibilidad)
        if form.is_valid() and form2.is_valid():
            form.save()
            form2.save()
            return HttpResponseRedirect(self.get_success_url())
        else:
            return HttpResponseRedirect(self.get_success_url())


class GetMedic(ListView):
    model = Availability
    template_name = 'assign.html'
    form_class = SetAvailableAppointments

    # form_class = 'SetAvailableAppointments'

    # def get(self, request, *args, **kwargs):
    # return render(request, 'assign.html', {'form': self.form_class})

    def post(self, request, *args, **kwargs):
        a = request.POST['date']
        c = request.POST['id_med2']

        print(a, c)
        return redirect('assigning/', *args, **kwargs)


class SetAvailableAppointments(CreateView):
    model = Appointment
    template_name = 'CEHN/cancelarcita.html'
    form_class = SetAvailableAppointments

    def prub(self):
        return HttpResponse('Hola')



@method_decorator([pacient_required], name='dispatch')
class Query_Medic(LoginRequiredMixin, ListView):
    model = Medic
    template_name = 'Assign/assign.html'


@method_decorator([admin_required], name='dispatch')
class Query_Interval(LoginRequiredMixin, ListView):
    model = Interval
    template_name = 'Assign/hours.html'


@method_decorator([pacient_required], name='dispatch')
class Query_Avail(LoginRequiredMixin, ListView):
    model = Availability
    template_name = 'Assign/avail.html'

    def post(self, *args, **kwargs):
        print(self.request)
        queryset = Availability.objects.filter(id_med2=self.request.POST['id_Medic'], date=self.request.POST['date'],
                                               state=True)
        if (queryset):
            return render(self.request, 'Assign/avail.html',
                          {'qsea': queryset, 'id_Medic': queryset.first().id_med2, 'date': self.request.POST['date'], \
                           'id_off': queryset.first().id_off2})
        else:
            return render(self.request, 'Assign/avail.html', {'no': 'no hay'})


@method_decorator([admin_required], name='dispatch')
class AvailabilityCreateView(LoginRequiredMixin, View):
    template_name = 'admin/create_availability.html'

    def get(self, request, *args, **kwargs):
        form = AvailabilityFormFull()
        context = {'form': form}
        return render(request, self.template_name, context)

    def post(self, request, *args, **kwargs):
        context = {}
        medic = request.POST['id_med2']
        office = request.POST['id_off2']
        intervalo = request.POST['id_inter1']
        date = request.POST['date']
        form = AvailabilityFormFull()
        if Availability.objects.filter(id_med2=medic, id_off2=office, id_inter1=intervalo, date=date):
            context['message'] = "Disponibilidad repetida"
            context['form'] = form
        elif Availability.objects.filter(id_off2=office, id_inter1=intervalo, date=date):
            context['message'] = "Oficina ocupada"
            context['form'] = form
        else:
            form = AvailabilityFormFull(request.POST)
            if form.is_valid():
                form.save()
                form = AvailabilityFormFull()
                context['message'] = "Disponibilidad creada con exito"
            context['form'] = form
        return render(request, self.template_name, context)


@method_decorator([pacient_required], name='dispatch')
class AssignView(LoginRequiredMixin, View):
    template_name = 'Assign/created_appointment.html'

    def post(self, request, *args, **kwargs):
        context = {}
        medic = request.POST['medico']
        office = request.POST['oficina']
        intervalo = request.POST['intervalo']
        date = request.POST['fecha']
        aval_id = get_object_or_404(Availability, id_med2=medic, id_off2=office, id_inter1=intervalo, date=date,
                                    state=True)
        pac = get_object_or_404(Pacient, userFK_id=self.request.user.id)

SitioMedico/templates/CEHN/actual_consul.html
{% extends 'base/base.html' %}

{% load static %}

{% block title %}CONSULTA MEDICA{% endblock %}
<body>
{% block body %}
<div class="login100-form-title" style="padding-bottom: 44px;">
    <h1>Consulta Externa Hospital Naval</h1>
</div>
<div class="login100-form-title" style="width: 20%;">
        <span class="login100-form-title">
						Hola, {{user.get_username}}.
					</span>
</div>
<div>
    <h1>Consulta Médica</h1>
</div>

<div class="login100-form-title" style="width: 20%;">
    <a href="{% url 'logout' %}?next=/login"><input type="image" height="35px"
                                                    src="{% static 'CEHN/images/icons/iconfinder_power_926636.png' %}"></a>
</div>
<div>
    <h3>Paciente:   {{ form.instance.id_appo2.id_pac1 }}</h3>
    <h3>Edad:       {{ form.instance.id_appo2.id_pac1.age }}</h3>
</div>

        <form method="post">
            {% csrf_token %}
            <table class="table table-dark table-striped table-hover text-center" border="1">
                <thead>
                    <td colspan="2"><h2>Anamnesis</h2></td>
                </thead>
                <tbody>
                    <tr>
                        <td>Sintomas: </td>
                        <td>{{ form.symptom }}</td>
                    </tr>
                    <tr>
                        <td>Diagnostico: </td>
                        <td>{{ form.diag }}</td>
                    </tr>
                </tbody>
            </table>
            <table class="table table-dark table-striped table-hover text-center" border="1">
                <thead>
                    <td><h2>Medicamentos</h2></td>
                    <td><a class="login100-form-btn"  href="{% url 'CEHN:medicamentos' form.instance.id_cons %}">Añadir</a></td>
                </thead>
                <tbody>
                    {% for m in medicamentos %}
                    <tr>
                        <td colspan="2"><h6>{{ m.medi.name }}</h6></td>
                    </tr>
                    {% empty %}
                    <tr>
                        <td colspan="2"><h5>No ha recetado ninguno</h5></td>
                    </tr>
                    {% endfor %}
                    <tr>
                        <td><input type="submit" value="guardar" class="login100-form-btn" style="border-radius: 25px;"></td>
                        <td><a class="login100-form-btn botonJaime" href="{% url 'CEHN:consultas' %}">Regresar</a></td>
                    </tr>
                </tbody>


            </table>

        </form>
{% endblock %}
</body>

SitioMedico/templates/CEHN/aplazacita.html
{% extends 'base/base.html' %}

{% load static %}

{% block title %}APLAZAR CITA{% endblock %}
<body>

{% block body %}

<!-- Modal -->

<div class="modal fade" id="myModal" role="dialog">
    <div class="modal-dialog">

        <!-- Modal content-->
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span
                       aria-hidden="true">&times;</span></button>
                <h4 class="modal-title" id="myModalLabel">Aplazar Cita</h4>
            </div>
            <div class="modal-body">
                Fecha: {{ form.instance.id_aval1.date }}<br>
                Hora: {{ form.instance.id_aval1.id_inter1.hour_start }}<br>
                Consultorio: {{ form.instance.id_aval1.id_off2.door_number }}<br>
                Medico: {{ form.instance.id_aval1.id_med2.name }}<br>
            </div>
            <div class="modal-footer">

                <form method="post">
                    {% csrf_token %}
                    {{ form.as_p }}
                    {{ form2.as_p }}
                    <button class="btn btn-default btn-outline-danger" type="submit" value="Cancelar">Aplazar</button>
                    <a class="btn btn-default btn-outline-success" href="{% url 'CEHN:citas' %}">REGRESAR</a>
                </form>
            </div>
        </div>

    </div>
</div>

<!-- End modal -->
<div>
    <h2>Si aplaza esta cita se cancelará y se redirigirá automaticamente para que aparte una nueva cita</h2>
</div>
<div class="login100-form-title">
    <center>
        <button style="width: 40%;" type="button" class="login100-form-btn botonJaime" data-toggle="modal"
                data-target="#myModal">
            ¿Desea Aplazar?
        </button><br>

        <a style="width: 40%" class="login100-form-btn botonJaime" href="{% url 'CEHN:citas' %}">Regresar</a>
    </center>

</div>


{% endblock %}

</body>

SitioMedico/templates/CEHN/cancelarcita.html
{% extends 'base/base.html' %}

{% load static %}

{% block title %}CANCELAR CITAS{% endblock %}
<body>

{% block body %}

<!-- Modal -->

<div class="modal fade" id="myModal" role="dialog">
    <div class="modal-dialog">

        <!-- Modal content-->
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span
                        aria-hidden="true">&times;</span></button>
                <h4 class="modal-title" id="myModalLabel">Cancelar cita</h4>
            </div>
            <div class="modal-body">
                Fecha: {{ form.instance.id_aval1.date }}<br>
                Hora: {{ form.instance.id_aval1.id_inter1.hour_start }}<br>
                Consultorio: {{ form.instance.id_aval1.id_off2.door_number }}<br>
                Medico: {{ form.instance.id_aval1.id_med2.name }}<br>
            </div>
            <div class="modal-footer">

                <form method="post">
                    {% csrf_token %}
                    {{ form.as_p }}
                    {{ form2.as_p }}
                    <button class="btn btn-default btn-outline-danger" type="submit" value="Cancelar">Cancelar</button>
                    <a class="btn btn-default btn-outline-success" href="{% url 'CEHN:citas' %}">REGRESAR</a>
                </form>
            </div>
        </div>

    </div>
</div>

<!-- End modal -->

<div class="login100-form-title">
    <center>
        <button style="width: 40%;" type="button" class="login100-form-btn botonJaime" data-toggle="modal"
                data-target="#myModal">
            ¿Desea cancelar?
        </button><br>

        <a style="width: 40%" class="login100-form-btn botonJaime" href="{% url 'CEHN:citas' %}">Regresar</a>
    </center>

</div>


{% endblock %}

</body>

SitioMedico/templates/CEHN/citas.html
{% extends 'base/base.html' %}

{% load static %}

{% block title %}GESTION CITAS{% endblock %}
<body>

{% block body %}

<div class="login100-form-title" style="padding-bottom: 44px;">
    <h1>Consulta Externa Hospital Naval</h1>
</div>

<div class="login100-form-title" style="width: 60%;">
    <a href="{% url 'CEHN:medic' %}" class="login100-form-btn" style="width: 50%">
        Apartar cita
    </a>
</div>

<div class="login100-form-title" style="width: 20%;">
        <span class="login100-form-title">
						Hola, {{user.get_username}}.
					</span>
</div>

<div class="login100-form-title" style="width: 20%;">
    <a href="{% url 'logout' %}?next=/login"><input type="image" height="35px"
                                                    src="{% static 'CEHN/images/icons/iconfinder_power_926636.png' %}"></a>
</div>

{% if object_list %}
<div class="login100-form-title" style="padding-bottom: 44px;">
    <h2>Citas apartadas</h2>
</div>
<table class="table table-dark table-striped table-hover text-center" border="1">
    <thead>
    <td>Fecha</td>
    <td>Hora</td>
    <td>Medico</td>
    <td colspan="2">Modificar</td>
    </thead>
    <tbody>
    {% for apo in object_list %}
    <tr>
        <td>{{ apo.id_aval1.date }}</td>
        <td>{{ apo.id_aval1.id_inter1 }}</td>
        <td>{{ apo.id_aval1.id_med2 }}</td>
        {% if apo.appointment == 'CF' %}
            <td colspan="2">Cita Confirmada</td>
        {% else %}
            <td>
                <a href="{% url 'CEHN:aplazar'  apo.id_appo %}" class="login100-form-btn" style="border-radius: 25px;">
                    Aplazar
                </a>
            </td>
            <td>

                <a class="login100-form-btn botonJaime" href="{% url 'CEHN:cancelar' apo.id_appo %}">Cancelar</a>
            </td>
        {% endif %}
    </tr>
    {% endfor %}

    </tbody>
</table>
{% else %}
<div class="login100-form-title" style="padding-bottom: 44px;">
    <h2>No tiene citas apartadas</h2>
</div>
{% endif %}
<script>

    $('#myModal').on('shown.bs.modal', function () {
        $('#myInput').trigger('focus')
    })

</script>
{% endblock %}

</body>

SitioMedico/templates/CEHN/confir_consul.html
{% extends 'base/base.html' %}

{% load static %}

{% block title %}CONFIRMAR CITA{% endblock %}
<body>
{% block body %}
    <div class="login100-form-title" style="padding-bottom: 44px;">
        <h1>Consulta Externa Hospital Naval</h1>
    </div>
   <form method="post">
       {% csrf_token %}
       {{ form.as_p }}
       <button type="submit" value="Confirmar" class="btn btn-default btn-outline-success">Confirmar</button>
       <a class="btn btn-default btn-outline-warning" href="{% url 'CEHN:medicos' %}">REGRESAR</a>
    </form>
{% endblock %}
</body>

SitioMedico/templates/CEHN/consulta.html
{% extends 'base/base.html' %}

{% load static %}

{% block title %}medical consultation{% endblock %}
<body>

{% block body %}

<div class="login100-form-title">
    <h1>Consulta Medica</h1>
</div>
<div class="login100-form-title text-center">
    <form action="." method="POST">
        {% csrf_token %}
            {{ form.as_p }}
            {{ form1.as_p}}
         <div class="container-login100-form-btn">
            <input class="login100-form-btn" style="width: 35%" type="submit" value="Enviar">
        </div>
    </form>
</div>
{% if message %}
<p>{{ message }}</p>
{% endif %}

<a href="{% url 'CEHN:home' %}"></a>
</body>
{% endblock %}

</html>

SitioMedico/templates/CEHN/consultas.html
{% extends 'base/base.html' %}

{% load static %}

{% block title %}CONSULTAS{% endblock %}
<body>
{% block body %}
    <div class="login100-form-title" style="padding-bottom: 44px;">
        <h1>Consulta Externa Hospital Naval</h1>
    </div>

    <div class="login100-form-title" style="width: 20%;">
        <span class="login100-form-title">
						Hola, {{user.get_username}}.
					</span>
    </div>
    <div class="login100-form-title" style="width: 20%;">
        <a href="{% url 'logout' %}?next=/login"><input type="image" height="35px"
                                                    src="{% static 'CEHN/images/icons/iconfinder_power_926636.png' %}"></a>
    </div>
    {% if object_list %}
    <div class="login100-form-title" style="padding-bottom: 44px;">
        <h2>Citas Programadas</h2>
    </div>
    <table class="table table-dark table-striped table-hover text-center" border="1">
        <thead>
            <td>Fecha</td>
            <td>Hora</td>
            <td>Paciente</td>
            <td>Accion</td>
        </thead>
        <tbody>
            {% for con in object_list %}
            <tr>
                <td>{{ con.id_appo2.id_aval1.date }}</td>
                <td>{{ con.id_appo2.id_aval1.id_inter1 }}</td>
                <td>{{ con.id_appo2.id_pac1 }}</td>
                <td><a class="login100-form-btn" href="{% url 'CEHN:actualconsul' con.id_cons %}">Atender</a></td>
            </tr>
            {% endfor %}

        </tbody>
    </table>
    {% else %}
    <div class="login100-form-title" style="padding-bottom: 44px;">
    <h2>No Tiene Consultas Programadas</h2>
</div>
    {% endif %}
{% endblock %}
</body>

SitioMedico/templates/CEHN/listacitas.html
{% extends 'base/base.html' %}

{% load static %}

{% block title %}CANCELAR CITAS{% endblock %}
<body>
{% block body %}
    <div class="login100-form-title" style="padding-bottom: 44px;">
        <h1>Consulta Externa Hospital Naval</h1>
    </div>
    {% if object_list %}
    <table class="table table-dark table-striped table-hover text-center" border="1">
        <thead>
        <tr>
            <td>Fecha</td>
            <td>Hora</td>
            <td>Paciente</td>
            <td colspan="2">Accion</td>
        </tr>
        </thead>
        {% for appo in object_list %}
        <tr>
            <td>{{ appo.id_aval1.date }}</td>
            <td>{{ appo.id_aval1.id_inter1 }}</td>
            <td>{{ appo.id_pac1.name }}</td>
            <td><a class="btn btn-default btn-outline-success" href="{% url 'CEHN:confirmconsul' appo.id_appo %}">Confirmar</a></td>
            <td><a class="btn btn-default btn-outline-danger" href="{% url 'CEHN:citaperdida' appo.id_appo %}">Perder</a></td>
        </tr>
        {% endfor%}
    </table>
    {% else %}
        <h2>No tiene Citas Apartadas para Hoy</h2>
    {% endif%}
{% endblock %}
</body>

SitioMedico/templates/CEHN/listamedicos.html
{% extends 'base/base.html' %}

{% load static %}

{% block title %}Lista Medicos{% endblock %}

<body>

{% block body %}
    <div class="login100-form-title" style="padding-bottom: 44px;">
        <h1>Consulta Externa Hospital Naval</h1>
    </div>
    {% if object_list %}
    <h2>Medicos</h2>
    <table class="table table-dark table-striped table-hover text-center" border="1">
        <thead>
            <td>Nombre</td>
            <td >Accion</td>
        </thead>
        <tbody>
            {% for medi in object_list %}
            <tr>
                <td>{{ medi.name }}</td>
                <td><a class="btn btn-default btn-outline-success" href="{% url 'CEHN:listacitas' medi.id_Medic %}">Consultar</a></td>
            </tr>
            {% endfor %}

        </tbody>
    </table>
    {% else %}
    <h2>No tiene citas programadas</h2>
    {% endif %}

{% endblock %}
{% block admin %} {% endblock %}

</body>

SitioMedico/templates/CEHN/medicamentos.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Medicamentos</title>
</head>
<body>
    <form method="post">
        {% csrf_token %}
        {{ form }}
        <input type="submit" value="Añadir">
    </form>
</body>
</html>

SitioMedico/templates/CEHN/miss_appo.html
{% extends 'base/base.html' %}

{% load static %}

{% block title %}PERDER CITAS{% endblock %}

<body>
{% block body %}
    <div class="login100-form-title" style="padding-bottom: 44px;">
        <h1>Consulta Externa Hospital Naval</h1>
    </div>
    Paciente: {{ form.instance.id_pac1.name }}<br>
    Fecha: {{ form.instance.id_aval1.date }}<br>
    Hora: {{ form.instance.id_aval1.id_inter1.hour_start }}<br>
    Consultorio: {{ form.instance.id_aval1.id_off2.door_number }}<br>
    Medico: {{ form.instance.id_aval1.id_med2.name }}<br>
     <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button class="btn btn-default btn-outline-danger" type="submit" value="Cancelar">Perder</button>
        <a class="btn btn-default btn-outline-success" href="{% url 'CEHN:medicos' %}">REGRESAR</a>
     </form>
{% endblock %}
</body>