SitioMedico/CEHN/urls.py
from django.urls import path
from . import views


from .views import Home, PacientCreate, MedicCreate, AdminCreate, CitasListas, CancelarCita, ConfirmConsulView, \
    Query_Medic, Query_Interval, Query_Avail, AssignView, ConsultasListas, listaMedicsView, ConsulUpdateView, \
    MedicaView, AvailabilityCreateView, MissAppoView, ListaCitasView, AplazaAppoView, GetMedic, SetAvailableAppointments

app_name = 'CEHN'
urlpatterns = [
    path('medics/', Query_Medic.as_view(), name='medic'),
    path('intervals/', Query_Interval.as_view(), name='intervals'),
    path('avail/assigns/', AssignView.as_view(), name="assigns"),
    path('asignar/', AssignView.as_view(), name="assign"),
    path('avail/', Query_Avail.as_view(), name='availabilities'),
    path('', Home.as_view(), name="home"),
    path('', views.login, name="login"),
    path('admin_registered/', views.admin_registered, name="admin_registered"),
    path('medic_registered/', views.medic_registered, name="medic_registered"),
    path('patient_registered/', views.patient_registered, name="patient_registered"),
    path('registrar/paciente', PacientCreate.as_view(), name="registar_paciente"),
    path('registrar/medico', MedicCreate.as_view(), name="registrar_medico"),
    path('registrar/admin', AdminCreate.as_view(), name="registrar_admin"),
    path('citas/', CitasListas.as_view(), name='citas'),
    path('cancelar/<pk>', CancelarCita.as_view(), name='cancelar'),
    path('aplazar/<pk>', AplazaAppoView.as_view(), name='aplazar'),
    path('create/availability/',AvailabilityCreateView.as_view(), name='create_availability'),
    path('consultas', ConsultasListas.as_view() ,name='consultas'),
    path('confirm/<apo>', ConfirmConsulView.as_view() ,name='confirmconsul'),
    path('medicos/',listaMedicsView.as_view(),name='medicos'),
    path('consulta/<pk>',ConsulUpdateView.as_view(), name='actualconsul'),
    path('medicamentos/<consult>', MedicaView.as_view(), name='medicamentos'),
    path('miss/<pk>', MissAppoView.as_view(), name='citaperdida'),
    path('listacitas/<medic>',ListaCitasView.as_view(), name='listacitas')
    # path('', views.index, name="index"),
    #path('dispo/<medic>',Dispo.as_view(),name='dispo'),
    #path('citas/<pacient>', CitasListas.as_view(), name='citas'),
    #url(r'cancelar/(?P<pk>\d+)$', CancelarCita.as_view(), name='cancelar'),
    # path('dispo/<medic>',Dispo.as_view(),name='dispo'),
    # path('citas/<pacient>', CitasListas.as_view(), name='citas'),
    # url(r'cancelar/(?P<pk>\d+)$', CancelarCita.as_view(), name='cancelar'),
    # path('dispo/<medic>',Dispo.as_view(),name='dispo'),
    # path('citas/<pacient>', CitasListas.as_view(), name='citas'),
    # url(r'cancelar/(?P<pk>\d+)$', CancelarCita.as_view(), name='cancelar'),
    # path('assign/', GetMedic.as_view(), name='assigning'),
    # path('assign/assigning/', SetAvailableAppointments.as_view(), name='assigning'),
]

SitioMedico/SitioMedico/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic.base import TemplateView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('django.contrib.auth.urls')),
    path('', include('CEHN.urls')),
    #path('assign/', TemplateView.as_view(template_name='assign.html'), name='assign'),
    path('', TemplateView.as_view(template_name='home.html'), name='home')
]

SitioMedico/templates/register/admin_register.html
{% extends 'base/base.html' %}

{% load static %}

{% block title %}ADMIN REGISTER{% endblock %}

<body>

{% block body %}
<div class="login100-form-title" >
    <a style="padding-right: 610px;" href="{% url 'logout' %}?next=/login"><input type="image" height="35px"
                                                    src="{% static 'CEHN/images/icons/iconfinder_power_926636.png' %}"></a>
    <a class="txt2" href="{% url 'CEHN:home' %}">
        Volver
    </a>
</div>
<div class="login100-form-title">
    <h1>Admin register</h1>
</div>
<div class="login100-form-title text-center">
    <form method="post">
        {% csrf_token %}
        <div class="wrap-input100 validate-input text-center">
            {{form.erros.username}}
            <label>Username</label>{{form.username}}<br>
            <label>Email</label>{{form.email}}<br>
            {{ form.errors.password2 }}
            <label>Password</label><input class="input100" {{form.password1}}<br><br>
            <label>Repeat password</label><input class="input100" {{form.password2}}<br>
        </div>
        <div class="container-login100-form-btn">
            <input class="login100-form-btn" style="width: 35%" type="submit" value="Enviar">
        </div>
    </form>
</div>


{% endblock %}
{% block extrajs %}
<script>
    // Funcion que se ejecuta cada vez que se pulsa una tecla en cualquier input
    // Tiene que recibir el "event" (evento generado) y el siguiente id donde poner
    // el foco. Si ese id es "submit" se envia el formulario
    function justNumbers(e) {
        var keynum = window.event ? window.event.keyCode : e.which;
        if ((keynum == 8) || (keynum == 46))
            return true;

        return /\d/.test(String.fromCharCode(keynum));
    }

    //La misma función que la anterior sólo que solo letras
    function soloLetras(e) {
        key = e.keyCode || e.which;
        tecla = String.fromCharCode(key).toLowerCase();
        letras = " áéíóúabcdefghijklmnñopqrstuvwxyz";
        especiales = "8-37-39-46";

        tecla_especial = false
        for (var i in especiales) {
            if (key == especiales[i]) {
                tecla_especial = true;
                break;
            }
        }

        if (letras.indexOf(tecla) == -1 && !tecla_especial) {
            return false;
        }
    }

    function saltar(e, id) {
        // Obtenemos la tecla pulsada
        (e.keyCode) ? k = e.keyCode : k = e.which;

        // Si la tecla pulsada es enter (codigo ascii 13)
        if (k == 13) {
            // Si la variable id contiene "submit" enviamos el formulario
            if (id == "submit") {
                document.forms[0].submit();
            } else {
                // nos posicionamos en el siguiente input
                document.getElementById(id).focus();
            }
        }
    }

</script>
{% endblock%}
</body>

SitioMedico/templates/register/admin_registered.html
{% extends 'base/base.html' %}

{% load static %}

{% block title %}Admin registered{% endblock %}
<body>

{% block body %}

<div class="login100-form-title text-success text-center">
    <h1>Admin registrado con exito</h1>
</div>
<div class="login100-form-title p-t-12">
    <a class="txt2" href="{% url 'CEHN:registrar_admin' %}">
        Volver
    </a>
</div>
{% endblock %}


</body>

SitioMedico/templates/register/medic_register.html
{% extends 'base/base.html' %}

{% load static %}

{% block title %}MEDIC REGISTER{% endblock %}

<body>

{% block body %}
<div class="login100-form-title" >
    <a style="padding-right: 610px;" href="{% url 'logout' %}?next=/login"><input type="image" height="35px"
                                                    src="{% static 'CEHN/images/icons/iconfinder_power_926636.png' %}"></a>
    <a class="txt2" href="{% url 'CEHN:home' %}">
        Volver
    </a>
</div>
<div class="login100-form-title">
    <h1>Medic register</h1>
</div>
<div class="login100-form-title text-center">
    <form method="post">
        {% csrf_token %}
        <div class="wrap-input100 validate-input text-center">
            <span>Name {{form.name}} </span><br>
            <span>First last name {{form.lastname1}} </span><br>
            <span>Second last name {{form.lastname2}} </span><br>
            {{ form.errors.identification }}
            <span>Identification {{form.identification}} </span><br>
            <span>Age {{form.age}} </span><br>
            <span>Sex </span><br>{{form.sex}} <br><br>
            <span>Phone {{form.phone}} </span><br>
            <span>Address {{form.address}} </span><br>
        </div>
        <div class="wrap-input100 validate-input text-left">
            <h1>User</h1>
        </div>
        <div class="wrap-input100 validate-input text-center">
            {{ form1.errors.username }}
            <label>Username</label>{{form1.username}}<br>
            <label>Email</label>{{form1.email}}<br>
            {{ form1.errors.password2 }}
            <label>Password</label><input class="input100" {{form1.password1}}<br>
            <label>Repeat password</label><input class="input100" {{form1.password2}}<br>
        </div>
        <div class="container-login100-form-btn">
            <input class="login100-form-btn" style="width: 35%" type="submit" value="Enviar">
        </div>
    </form>
</div>


{% endblock %}
{% block extrajs %}
<script>
    // Funcion que se ejecuta cada vez que se pulsa una tecla en cualquier input
    // Tiene que recibir el "event" (evento generado) y el siguiente id donde poner
    // el foco. Si ese id es "submit" se envia el formulario
    function justNumbers(e) {
        var keynum = window.event ? window.event.keyCode : e.which;
        if ((keynum == 8) || (keynum == 46))
            return true;

        return /\d/.test(String.fromCharCode(keynum));
    }

    //La misma función que la anterior sólo que solo letras
    function soloLetras(e) {
        key = e.keyCode || e.which;
        tecla = String.fromCharCode(key).toLowerCase();
        letras = " áéíóúabcdefghijklmnñopqrstuvwxyz";
        especiales = "8-37-39-46";

        tecla_especial = false
        for (var i in especiales) {
            if (key == especiales[i]) {
                tecla_especial = true;
                break;
            }
        }

        if (letras.indexOf(tecla) == -1 && !tecla_especial) {
            return false;
        }
    }

    function saltar(e, id) {
        // Obtenemos la tecla pulsada
        (e.keyCode) ? k = e.keyCode : k = e.which;

        // Si la tecla pulsada es enter (codigo ascii 13)
        if (k == 13) {
            // Si la variable id contiene "submit" enviamos el formulario
            if (id == "submit") {
                document.forms[0].submit();
            } else {
                // nos posicionamos en el siguiente input
                document.getElementById(id).focus();
            }
        }
    }

</script>
{% endblock%}
</body>

SitioMedico/templates/register/medic_registered.html
{% extends 'base/base.html' %}

{% load static %}

{% block title %}Medic registered{% endblock %}
<body>

{% block body %}

<div class="login100-form-title text-success text-center">
    <h1>Medico registrado con exito</h1>
</div>

<div class="login100-form-title p-t-12">
    <a class="txt2" href="{% url 'CEHN:registrar_medico' %}">
        Volver
    </a>
</div>

{% endblock %}


</body>

SitioMedico/templates/register/patient_register.html
{% extends 'base/base.html' %}

{% load static %}

{% block title %}PATIENT REGISTER{% endblock %}

<body>

{% block body %}
<div class="login100-form-title" >
    <a style="padding-right: 610px;" href="{% url 'logout' %}?next=/login"><input type="image" height="35px"
                                                    src="{% static 'CEHN/images/icons/iconfinder_power_926636.png' %}"></a>
    <a class="txt2" href="{% url 'CEHN:home' %}">
        Volver
    </a>
</div>
<div class="login100-form-title">
    <h1>Patient register</h1>
</div>
<div class="login100-form-title text-center">
    <form method="post">
        {% csrf_token %}
        <div class="wrap-input100 validate-input text-center">
            <span>Name {{form.name}} </span><br>
            <span>First last name {{form.lastname1}} </span><br>
            <span>Second last name {{form.lastname2}} </span><br>
            {{ form.errors.identification }}
            <span>Identification {{form.identification}} </span><br>
            <span>Age {{form.age}} </span><br>
            <span>Sex </span><br>{{form.sex}} <br><br>
            <span>Phone {{form.phone}} </span><br>
            <span>Address {{form.address}} </span><br>
        </div>
        <div class="wrap-input100 validate-input text-left">
            <h1>User</h1>
        </div>
        <div class="wrap-input100 validate-input text-center">
            {{ form.errors.username }}
            <label>Username</label>{{form1.username}}<br>
            <label>Email</label>{{form1.email}}<br>
            {{ form.errors.password2 }}
            <label>Password</label><input class="input100" {{form1.password1}}<br>
            <label>Repeat password</label><input class="input100" {{form1.password2}}<br>
        </div>
        <div class="container-login100-form-btn">
            <input class="login100-form-btn" style="width: 35%" type="submit" value="Enviar">
        </div>
    </form>
</div>


{% endblock %}
{% block extrajs %}
<script>
    // Funcion que se ejecuta cada vez que se pulsa una tecla en cualquier input
    // Tiene que recibir el "event" (evento generado) y el siguiente id donde poner
    // el foco. Si ese id es "submit" se envia el formulario
    function justNumbers(e) {
        var keynum = window.event ? window.event.keyCode : e.which;
        if ((keynum == 8) || (keynum == 46))
            return true;

        return /\d/.test(String.fromCharCode(keynum));
    }

    //La misma función que la anterior sólo que solo letras
    function soloLetras(e) {
        key = e.keyCode || e.which;
        tecla = String.fromCharCode(key).toLowerCase();
        letras = " áéíóúabcdefghijklmnñopqrstuvwxyz";
        especiales = "8-37-39-46";

        tecla_especial = false
        for (var i in especiales) {
            if (key == especiales[i]) {
                tecla_especial = true;
                break;
            }
        }

        if (letras.indexOf(tecla) == -1 && !tecla_especial) {
            return false;
        }
    }

    function saltar(e, id) {
        // Obtenemos la tecla pulsada
        (e.keyCode) ? k = e.keyCode : k = e.which;

        // Si la tecla pulsada es enter (codigo ascii 13)
        if (k == 13) {
            // Si la variable id contiene "submit" enviamos el formulario
            if (id == "submit") {
                document.forms[0].submit();
            } else {
                // nos posicionamos en el siguiente input
                document.getElementById(id).focus();
            }
        }
    }

</script>
{% endblock%}
</body>

SitioMedico/templates/register/patient_registered.html
{% extends 'base/base.html' %}

{% load static %}

{% block title %}Patient registered{% endblock %}
<body>

{% block body %}

<div class="login100-form-title text-success text-center">
    <h1>Paciente registrado con exito</h1>
</div>
<div class="login100-form-title p-t-12">
    <a class="txt2" href="{% url 'CEHN:registar_paciente' %}">
        Volver
    </a>
</div>
{% endblock %}


</body>